### ISSUE TITLE
Unhandled exception downloading from Bluemix liberty app

### ISSUE THREAD

**Issue by nanowireUK** [ibmjstart/cf-download#3]
When downloading an app and ignoring the advice to omit /app/.java and /app/.liberty I was getting unhandled exceptions that "". This broke the download and meant restarting.

After omiting those folders I got a similar (but different) error for a different file which also caused the whole operation to fail leading to a redownload.

Pretty sure the problems with the files is within Bluemix but these errors should still have been caught and handled rather than causing the whole operation to fail

**Comment by jlstack** [comment]
Hello nanowireUK,

I am trying to track down where this issue may have occurred but have a few questions for you. 
- Have you tried the plugin lately and are you still experiencing the same behavior?  
- How did you deploy your application? Was it the sample app you get from the "Liberty for Java" runtime on Bluemix?
- Is anything printed other than an empty string? 
- What operating system are you using?

Sincerely,
Luke Stack

**Comment by nanowireUK** [comment]
Hi Luke,

I used the latest version of the plugin, downloaded on the day of making the report.

Apologies for the empty string, there was a proper error but it doesn't seem to have pasted in correctly. The issue I'm trying to raise is not that there was a problem downloading a particular file but that the whole process aborted in response to an unhandled error on a single file (I saw this with at least two different errors).

The tool should have a 'ignore file errors' option so that any isolated issues doesn't impact the full job.

Using Windows 7 64bit.

Best regards,

Phil

**Comment by jlstack** [comment]
Phil,

Could you try to replicate your experience and provide the proper error that was given? That way I can have some context as to where and why the error was raised and try to handle it in a more graceful manner.

Thanks,
Luke

**Comment by nanowireUK** [comment]
Hi Luke,

Just tried it again and got the following error when downloading .liberty (which I know isn't recommended to download):
fatal error: runtime: cannot map pages in arena address space
[stack.txt](https://github.com/ibmjstart/cf-download/files/303027/stack.txt)

Like I say, the actual error message for the file isn't particularly relevant (I got two different uncaught errors). What I'm suggesting is that there needs to be a flag to 'ignore file errors' and put a catch all in that simply moves on to the next file. My repository contains over 3,000 files and I had to restart 5 times at different stages, each time adding a new omit path before I could finally get all the non-error files.

Thanks,

Phil

**Comment by jlstack** [comment]
Phil,

I understand what you are asking for, but I still need addition information to know where these errors are coming from and how they can be omitted. Would you be willing to run the download command with the "--verbose" option so that I can have more information to help debug this issue? If you could run 

`cf download YOUR_APP_HERE --verbose > log.txt`

and send me log.txt, It would be greatly appreciated. If you feel more comfortable emailing it to me, you can. My email is lstack@us.ibm.com.

Thanks,
Luke

**Comment by nanowireUK** [comment]
Hi Luke,

Of course. I've been trying to replicate the same error but so far no success (I suspect it might be something like a transient filesystem lock). In trying to replicate I have however three different file level errors that all caused the whole process to abort. In two of the cases I would have wanted the job to continue on best effort.

First time around it lost network connection (so failing job is appropriate).
[log.txt](https://github.com/ibmjstart/cf-download/files/303012/log.txt)

Second time, no idea what happened - says a bug in cf: invalid memory address or nil pointer dereference
[log4.txt](https://github.com/ibmjstart/cf-download/files/303013/log4.txt)

Next time I omitted /app/.java and got the following error instead (file name too long):
[log6.txt](https://github.com/ibmjstart/cf-download/files/303014/log6.txt)

Thanks,

Phil

**Comment by nanowireUK** [comment]
Didn't mean to close

**Comment by jlstack** [comment]
Phil,

I looked at your logs and have made several modifications to the plugin since. First, I would ask that you install the latest version of the CLI. In log4.txt you experience an error when `cf files client-poc /app/.java/jre/lib/rt.jar -i 0` was called. I too experienced this, but the problem seemed to resolve itself when I updated the CLI. I believe that the mkdir issue experienced in log6.txt was a result of a bad path that mixed both forward and backward slashes. This should be resolved with my changes. Lastly, I tried to make the plugin more flexible altogether in it's error handling.

I'd be very appreciative if you could uninstall and re-install the plugin using the latest binaries. I tested the plugin on a Windows VM, but I'd love any additional feedback from actual Windows users.

Thanks,
Luke

**Comment by nanowireUK** [comment]
Hi Luke,

Tried to do as you requested but unfortunately fell at the first hurdle. I uninstalled the old version and then got the following when I ran `cf install-plugin cf-download -r CF-Community`:

```
Looking up 'cf-download' from repository 'CF-Community'
9573888 bytes downloaded...
FAILED
Downloaded plugin binary's checksum does not match repo metadata
```

Result from `cf list-plugin-repo` is

```
Repo Name      Url
CF-Community   http://plugins.cloudfoundry.org/
```

**Comment by jlstack** [comment]
Phil,

There is currently an [open pull request](https://github.com/cloudfoundry-incubator/cli-plugin-repo/pull/76) to update the binary checksum to match the latest release. Until the pull request is accepted, you must install the plugin using the binary directly. The README has instructions on how to do so [here](https://github.com/ibmjstart/cf-download#install-from-binary).

**Comment by jlstack** [comment]
The pull request was merged with the CF-Community repo yesterday. You should now be able to install the plugin the same way you tried before.

**Comment by nanowireUK** [comment]
Tested this out today and saw no issues so closing. Have opened separate issue on CPU usage whilst downloading
