### ISSUE TITLE
High CPU load on MacOS

### ISSUE THREAD

**Issue by nanowireUK** [ibmjstart/cf-download#9]
Installed cf and cf-download using Homebrew on MacOS.

System is a Macbook Pro with i7 and 16GB RAM.

Tried downloading a large cf app and it started using near 100% CPU time. In Activity Monitor I can see that this is spawning a huge number of individual cf processes, each with 12 - 16 threads.

<img width="1920" alt="screen shot 2016-09-27 at 12 08 09" src="https://cloud.githubusercontent.com/assets/6579068/18870976/2591807e-84ab-11e6-9639-cea9dc4f4b98.png">

On cancelling the download it instantly killed over 3,000 threads and 250 processes (plus my laptop stopped trying to take off with the fans running at full pelt).

**Comment by reSoley** [comment]
It looks to me like the issue is at lines [83](https://github.com/ibmjstart/cf-download/blob/master/downloader/download.go#L83) and [101](https://github.com/ibmjstart/cf-download/blob/master/downloader/download.go#L101) of download.go where the go routines are starting up. There's no limit to their number and they are also being nested within one another.

**Comment by reSoley** [comment]
Pushed a real tiny change to the issue_9 branch that should stop it from hogging your whole CPU for now. I'm looking for a better solution.
